### ISSUE TITLE
Spanish / Vietnamese translation for city documents 

### ISSUE THREAD

**Issue by krammy19** [codeforsanjose/city-agenda-scraper#26]
Code for San Jose is applying for grant funding to expand translation services for city meetings. As part of this initiative, they want to see if we can include Spanish and Vietnamese translation in the agenda scraper project. 

For this service, we would perform translation on the following documents that will be scraped regularly: 

- City Agendas, examples found [here](https://github.com/codeforsanjose/city-agenda-scraper/tree/main/Agenda_samples)
- Staff reports, examples found [here](https://github.com/codeforsanjose/city-agenda-scraper/tree/main/Report_samples)
- Meeting minutes, example [here](https://sanjose.legistar.com/View.ashx?M=M&ID=853198&GUID=7DAFADE9-69D9-48FB-9103-95EFC734E268)

In this initial phase, we need estimates on the cost and time to add a translation script into our project. As this grant will be used exclusively for San Jose, this translation script will need to be optional for running our code for other cities.

**Comment by mkumar10** [comment]
[Translation_Cost_Analysis.pdf](https://github.com/codeforsanjose/city-agenda-scraper/files/6556932/Translation_Cost_Analysis.pdf)
Seems like after doing analysis for just `City Agendas` and `Staff Reports` - it comes down to free only for both languages as first 500k chars are free and `$20 per million subsequent characters`. I will convert meeting minutes doc from `pdf` to `txt` later tonight and add it to the analysis.

**Comment by mkumar10** [comment]
Note this was under the assumption that all text files were extracted `properly/close to perfect` from the pdfs but seems like that's not the case so this is not accurate w.r.t. pdfs but accurate w.r.t. text files in the sub-folder.
