### ISSUE TITLE
Bug fixes / Updates for Legistar_Selenium scraper

### ISSUE THREAD

**Issue by krammy19** [codeforsanjose/city-agenda-scraper#27]
Our Legistar_Selenium scraper has a few bugs that make it unable to work with certain cities. 

@mgarcia707 found a bug when he tested the code on San Jose associated with a list error on the line 49 loop. Please include specifics on this error in the comments. 

@krammy19 found a list error bug when he tested the code on Sunnyvale associated with the tables[11] on line 92.

**Comment by mgarcia707** [comment]
Please see error below when running code for https://sanjose.legistar.com/Calendar.aspx:
![image](https://user-images.githubusercontent.com/16787217/120729568-57130400-c494-11eb-872a-2ff0facbc34c.png)
